-- =============================================
-- XGuard Coaching System Schema
-- Generated: 2026-03-24
-- Tracks Nitro cron sync results, weekly AI coaching
-- reports, transcription progress, and cron logs.
-- =============================================
-- Run this in Supabase SQL Editor (Dashboard > SQL Editor)
-- Safe to re-run: uses IF NOT EXISTS and DROP POLICY IF EXISTS
-- Requires: people table from supabase_setup.sql
-- =============================================

-- =============================================
-- 1. COACHING_DATA
-- Daily sync results pushed by Nitro crons.
-- One row per person per day — captures call counts,
-- durations, source system, call breakdown by program,
-- and pipeline snapshot for that day.
-- =============================================
CREATE TABLE IF NOT EXISTS coaching_data (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id         TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  sync_date         DATE NOT NULL,
  calls_total       INTEGER DEFAULT 0,        -- total calls found that day
  calls_transcribed INTEGER DEFAULT 0,
  calls_new         INTEGER DEFAULT 0,        -- new calls since last sync
  avg_duration_sec  INTEGER DEFAULT 0,
  source            TEXT,                      -- 'justcall' or 'ghl'
  -- Call breakdown by program, e.g. {"drone": 15, "elite": 8, "autre": 2}
  call_breakdown    JSONB DEFAULT '{}',
  -- Pipeline snapshot: stages, conversion rate, etc.
  pipeline_stats    JSONB DEFAULT '{}',
  created_at        TIMESTAMPTZ DEFAULT now(),
  UNIQUE (person_id, sync_date)
);

-- =============================================
-- 2. COACHING_REPORTS
-- Weekly coaching analysis reports generated by AI.
-- One row per person per week — contains 8-dimension
-- scores, strengths, improvements, objections, and
-- week-over-week comparison data.
-- =============================================
CREATE TABLE IF NOT EXISTS coaching_reports (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id            TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  week_start           DATE NOT NULL,
  week_end             DATE NOT NULL,
  report_type          TEXT,                   -- 'ventes', 'ventes_drone', 'sac'
  -- 8 coaching dimensions: intro, qualification, objections, closing,
  -- empathy, energy, duration, engagement — each scored 0-10
  scores               JSONB DEFAULT '{}',
  calls_analyzed       INTEGER DEFAULT 0,
  avg_call_duration_sec INTEGER DEFAULT 0,
  top_objections       JSONB DEFAULT '[]',
  strengths            JSONB DEFAULT '[]',
  improvements         JSONB DEFAULT '[]',
  recommendations      JSONB DEFAULT '[]',
  -- vs previous week: score_delta, calls_delta, etc.
  comparison           JSONB DEFAULT '{}',
  -- Call breakdown by program (drone vs elite for Domingos)
  call_breakdown       JSONB DEFAULT '{}',
  -- Pipeline stats aggregated for the week
  pipeline_weekly      JSONB DEFAULT '{}',
  raw_summary          TEXT,                   -- full AI-generated text summary
  created_at           TIMESTAMPTZ DEFAULT now(),
  UNIQUE (person_id, week_start)
);

-- =============================================
-- 3. NITRO_STATUS
-- Real-time Nitro transcription progress.
-- One row per person per task type — updated live
-- while Nitro GPU is running transcriptions.
-- =============================================
CREATE TABLE IF NOT EXISTS nitro_status (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  task_type     TEXT NOT NULL,                -- 'daily_sync', 'weekly_report', 'batch_transcribe'
  status        TEXT DEFAULT 'idle',          -- 'idle', 'running', 'done', 'error'
  done          INTEGER DEFAULT 0,
  total         INTEGER DEFAULT 0,
  pct           REAL DEFAULT 0,
  gpu_active    BOOLEAN DEFAULT false,
  avg_speed_sec REAL DEFAULT 0,
  eta_label     TEXT DEFAULT '',
  last_file     TEXT DEFAULT '',
  error_msg     TEXT,
  started_at    TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE (person_id, task_type)
);

-- =============================================
-- 4. CRON_LOGS
-- Track cron execution history (admin only).
-- One row per cron run — logs duration, counts,
-- and any errors for debugging.
-- =============================================
CREATE TABLE IF NOT EXISTS cron_logs (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  person_id        TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  cron_type        TEXT NOT NULL,             -- 'daily_sync', 'weekly_report'
  status           TEXT DEFAULT 'running',    -- 'running', 'success', 'error'
  calls_processed  INTEGER DEFAULT 0,
  transcripts_new  INTEGER DEFAULT 0,
  error_msg        TEXT,
  duration_sec     INTEGER DEFAULT 0,
  started_at       TIMESTAMPTZ DEFAULT now(),
  finished_at      TIMESTAMPTZ
);

-- =============================================
-- 5. WATCHDOG_HEARTBEAT
-- Tracks the Nitro watchdog service health.
-- Single row (id='nitro') updated every 5 min.
-- Frontend uses this to show Nitro online/offline status.
-- =============================================
CREATE TABLE IF NOT EXISTS watchdog_heartbeat (
  id              TEXT PRIMARY KEY DEFAULT 'nitro',
  status          TEXT DEFAULT 'alive',        -- 'alive', 'starting', 'shutdown'
  started_at      TIMESTAMPTZ,
  last_heartbeat  TIMESTAMPTZ,
  uptime_sec      INTEGER DEFAULT 0,
  next_jobs       JSONB DEFAULT '[]',          -- [{id, next}]
  disk_free_mb    INTEGER DEFAULT 0,
  version         TEXT DEFAULT '1.0',
  error_msg       TEXT
);

-- =============================================
-- 6. ROW LEVEL SECURITY
-- All tables open (internal tool, no auth layer)
-- =============================================
ALTER TABLE coaching_data    ENABLE ROW LEVEL SECURITY;
ALTER TABLE coaching_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE nitro_status     ENABLE ROW LEVEL SECURITY;
ALTER TABLE cron_logs              ENABLE ROW LEVEL SECURITY;
ALTER TABLE watchdog_heartbeat     ENABLE ROW LEVEL SECURITY;

-- Drop and recreate policies to avoid duplicate errors on re-run
DO $$
BEGIN
  -- coaching_data
  DROP POLICY IF EXISTS "public all" ON coaching_data;
  CREATE POLICY "public all" ON coaching_data FOR ALL USING (true) WITH CHECK (true);

  -- coaching_reports
  DROP POLICY IF EXISTS "public all" ON coaching_reports;
  CREATE POLICY "public all" ON coaching_reports FOR ALL USING (true) WITH CHECK (true);

  -- nitro_status
  DROP POLICY IF EXISTS "public all" ON nitro_status;
  CREATE POLICY "public all" ON nitro_status FOR ALL USING (true) WITH CHECK (true);

  -- cron_logs
  DROP POLICY IF EXISTS "public all" ON cron_logs;
  CREATE POLICY "public all" ON cron_logs FOR ALL USING (true) WITH CHECK (true);

  -- watchdog_heartbeat
  DROP POLICY IF EXISTS "public all" ON watchdog_heartbeat;
  CREATE POLICY "public all" ON watchdog_heartbeat FOR ALL USING (true) WITH CHECK (true);
END $$;

-- =============================================
-- 6. INDEXES
-- =============================================
-- coaching_data: fast lookups by person and date
CREATE INDEX IF NOT EXISTS idx_coaching_data_person_id
  ON coaching_data (person_id);

CREATE INDEX IF NOT EXISTS idx_coaching_data_sync_date
  ON coaching_data (sync_date);

CREATE INDEX IF NOT EXISTS idx_coaching_data_person_date
  ON coaching_data (person_id, sync_date);

-- coaching_reports: fast lookups by person and week
CREATE INDEX IF NOT EXISTS idx_coaching_reports_person_id
  ON coaching_reports (person_id);

CREATE INDEX IF NOT EXISTS idx_coaching_reports_week_start
  ON coaching_reports (week_start);

CREATE INDEX IF NOT EXISTS idx_coaching_reports_person_week
  ON coaching_reports (person_id, week_start);

-- nitro_status: fast lookups by person
CREATE INDEX IF NOT EXISTS idx_nitro_status_person_id
  ON nitro_status (person_id);

-- cron_logs: fast lookups by person and type
CREATE INDEX IF NOT EXISTS idx_cron_logs_person_id
  ON cron_logs (person_id);

CREATE INDEX IF NOT EXISTS idx_cron_logs_cron_type
  ON cron_logs (cron_type);

-- =============================================
-- 7. REALTIME
-- =============================================
ALTER PUBLICATION supabase_realtime ADD TABLE coaching_data;
ALTER PUBLICATION supabase_realtime ADD TABLE coaching_reports;
ALTER PUBLICATION supabase_realtime ADD TABLE nitro_status;
ALTER PUBLICATION supabase_realtime ADD TABLE cron_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE watchdog_heartbeat;

-- =============================================
-- END OF SCHEMA
-- =============================================
